> Feedeliza+@1.0.0 start
> node backend/server.js
Swagger JSDoc options.apis: [ '/app/backend/routes/*.js' ]
Generated Swagger Specs (first 500 chars): {
  "openapi": "3.0.0",
  "info": {
    "title": "Check Test API",
    "version": "1.0.0",
    "description": "API documentation for the Check Test application."
  },
  "servers": [
    {
      "url": "http://localhost:5000/api",
      "description": "Production server"
    }
  ],
  "tags": [
    {
      "name": "Public API",
      "description": "Endpoints acessÃ­veis via API Token para integraÃ§Ã£o externa."
    },
    {
      "name": "Admin",
      "description": "Gerenciamento de usuÃ¡rios e res
âœ… ConexÃ£o com banco de dados estabelecida
ðŸš€ Servidor rodando na porta 5000
ðŸ“Š Dashboard: https://feedelizapro.towersfy.com
ðŸ”— API: https://feedelizaapi.towersfy.com/api
Erro ao buscar clientes: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.rawSelect (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:434:18)
    at async Customer.aggregate (/app/node_modules/sequelize/lib/model.js:1277:19)
    at async Customer.count (/app/node_modules/sequelize/lib/model.js:1306:20)
    at async Promise.all (index 0)
    at async Customer.findAndCountAll (/app/node_modules/sequelize/lib/model.js:1322:27)
    at async /app/backend/routes/customers.js:320:29 {
  name: 'SequelizeDatabaseError',
  parent: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  original: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
  parameters: {}
}
Erro ao buscar clientes: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Customer.findAll (/app/node_modules/sequelize/lib/model.js:1140:21)
    at async Promise.all (index 1)
    at async Customer.findAndCountAll (/app/node_modules/sequelize/lib/model.js:1322:27)
    at async /app/backend/routes/customers.js:320:29 {
  name: 'SequelizeDatabaseError',
  parent: error: column "restaurant_id" does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 114,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '749',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "id", "name", "email", "phone", "cpf", "whatsapp", "birth_date", "gender", "avatar", "preferences", "loyalty_points", "total_visits", "total_spent", "average_rating_given", "last_visit", "first_visit", "customer_segment", "status", "source", "referral_code", "referred_by", "notes", "tags", "marketing_consent", "email_verified", "phone_verified", "gdpr_consent", "gdpr_consent_date", "last_birthday_message_year", "metadata", "rfv_score", "nps_segment", "last_purchase_date", "total_orders", "average_ticket", "last_ticket_value", "most_bought_products", "most_bought_categories", "purchase_behavior_tags", "location_details", "preferred_communication_channel", "campaign_interaction_history", "last_survey_completed_at", "last_survey_id", "restaurant_id", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' ORDER BY "createdAt" ASC LIMIT 10 OFFSET 0;`,
    parameters: undefined
  },
  original: error: column "restaurant_id" does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 114,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '749',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "id", "name", "email", "phone", "cpf", "whatsapp", "birth_date", "gender", "avatar", "preferences", "loyalty_points", "total_visits", "total_spent", "average_rating_given", "last_visit", "first_visit", "customer_segment", "status", "source", "referral_code", "referred_by", "notes", "tags", "marketing_consent", "email_verified", "phone_verified", "gdpr_consent", "gdpr_consent_date", "last_birthday_message_year", "metadata", "rfv_score", "nps_segment", "last_purchase_date", "total_orders", "average_ticket", "last_ticket_value", "most_bought_products", "most_bought_categories", "purchase_behavior_tags", "location_details", "preferred_communication_channel", "campaign_interaction_history", "last_survey_completed_at", "last_survey_id", "restaurant_id", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' ORDER BY "createdAt" ASC LIMIT 10 OFFSET 0;`,
    parameters: undefined
  },
  sql: `SELECT "id", "name", "email", "phone", "cpf", "whatsapp", "birth_date", "gender", "avatar", "preferences", "loyalty_points", "total_visits", "total_spent", "average_rating_given", "last_visit", "first_visit", "customer_segment", "status", "source", "referral_code", "referred_by", "notes", "tags", "marketing_consent", "email_verified", "phone_verified", "gdpr_consent", "gdpr_consent_date", "last_birthday_message_year", "metadata", "rfv_score", "nps_segment", "last_purchase_date", "total_orders", "average_ticket", "last_ticket_value", "most_bought_products", "most_bought_categories", "purchase_behavior_tags", "location_details", "preferred_communication_channel", "campaign_interaction_history", "last_survey_completed_at", "last_survey_id", "restaurant_id", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' ORDER BY "createdAt" ASC LIMIT 10 OFFSET 0;`,
  parameters: {}
}
Erro ao buscar dados do dashboard: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Customer.findAll (/app/node_modules/sequelize/lib/model.js:1140:21)
    at async /app/backend/routes/dashboard.js:163:26 {
  name: 'SequelizeDatabaseError',
  parent: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '442',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:16:01.357 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
    parameters: undefined
  },
  original: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '442',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:16:01.357 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
    parameters: undefined
  },
  sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:16:01.357 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
  parameters: {}
}
totalCheckins: 0
mostFrequentCustomers: []
averageVisitDuration: { avg_duration_seconds: null }
checkinsByDay: []
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
Erro ao buscar dados do dashboard: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Customer.findAll (/app/node_modules/sequelize/lib/model.js:1140:21)
    at async /app/backend/routes/dashboard.js:163:26 {
  name: 'SequelizeDatabaseError',
  parent: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '442',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:17:08.490 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
    parameters: undefined
  },
  original: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 121,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '442',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:17:08.490 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
    parameters: undefined
  },
  sql: `SELECT "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment", COUNT("feedbacks"."id") AS "feedback_count", AVG("feedbacks"."rating") AS "avg_rating" FROM "customers" AS "Customer" INNER JOIN "feedbacks" AS "feedbacks" ON "Customer"."id" = "feedbacks"."customer_id" AND "feedbacks"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' AND "feedbacks"."created_at" >= '2025-07-16 01:17:08.490 +00:00' WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda' GROUP BY "Customer"."id", "Customer"."name", "Customer"."email", "Customer"."customer_segment" ORDER BY feedback_count DESC LIMIT 10;`,
  parameters: {}
}
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/roma-pizzaria
[Public Route] Restaurante roma-pizzaria nÃ£o encontrado.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/roma-pizzaria
[Public Route] Restaurante roma-pizzaria nÃ£o encontrado.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
[Public Route] Recebida requisiÃ§Ã£o para /restaurant/towersfy
[Public Route] Restaurante towersfy encontrado. Retornando dados.
Erro ao buscar clientes: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.rawSelect (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:434:18)
    at async Customer.aggregate (/app/node_modules/sequelize/lib/model.js:1277:19)
    at async Customer.count (/app/node_modules/sequelize/lib/model.js:1306:20)
    at async Promise.all (index 0)
    at async Customer.findAndCountAll (/app/node_modules/sequelize/lib/model.js:1322:27)
    at async /app/backend/routes/customers.js:320:29 {
  name: 'SequelizeDatabaseError',
  parent: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  original: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
  parameters: {}
}
Erro ao buscar clientes: Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.rawSelect (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:434:18)
    at async Customer.aggregate (/app/node_modules/sequelize/lib/model.js:1277:19)
    at async Customer.count (/app/node_modules/sequelize/lib/model.js:1306:20)
    at async Promise.all (index 0)
    at async Customer.findAndCountAll (/app/node_modules/sequelize/lib/model.js:1322:27)
    at async /app/backend/routes/customers.js:320:29 {
  name: 'SequelizeDatabaseError',
  parent: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  original: error: column Customer.restaurant_id does not exist
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '65',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn',
    sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
    parameters: undefined
  },
  sql: `SELECT count(*) AS "count" FROM "customers" AS "Customer" WHERE "Customer"."restaurant_id" = '219289ba-d468-4b6f-b4ce-dc386fa4bbda';`,
  parameters: {}
}